### PR TITLE
To make our commit numbers level

### PR DESCRIPTION
**Pull request by claywahlstrom**
So far, I have been merging your changes into mine and committing to my origin. Despite having the almost exact code, it says I'm 16 commits ahead. Other than that, keep it up! We've pushed through the hard part of setting the classes up so now it should be easier

### CODE REVIEW

**Comment by dyoburon** [comment]
What exactly would this merge add? Just seems like spacing stuff

**Comment by claywahlstrom** [comment]
Yes, there were some automatically generated spaces. I'm not sure if you
want to merge our histories together or not...

**Comment by dyoburon** [comment]
It looks kinda messy, you can use your command line to clear out the history for the stuff that isnt actually changing the files too much. But yeah, then I'll merge the spaces. I just dont want the change history to be spammed with a bunch of things that add like a couple spaces.

**Comment by claywahlstrom** [comment]
Sounds good, I'll clean it up tomorrow. Goodnight

**Comment by TheNamesDyl** [comment]
Night

**Pull request closed without merging**
